name: "Release"

on: workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Instal Dependencies
              run: npm ci