name: "Release"

on: workflow_dispatch

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v5

            - name: Instal Dependencies
              run: npm ci

            - name: Initialize Git User
              run: |
                git config --global user.email "sessionsbot@sessionsbot.fyi"
                git config --global user.name "Sessions Bot - Releases"

            - name: Publish Release
              run: npx release-it
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Completed
              run: echo 🚀 Release Published