name: Manual - Label Sync

on:
  workflow_dispatch:
    inputs:
      deleteUnmatched:
        description: 'Delete lables not in config?'
        options:
          - 'Delete Unmatched'
          - 'Keep Unmatched'
        type: choice
        required: true
        default: 'Delete Unmatched'

permissions:
  issues: write

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout - Config repository
        uses: actions/checkout@v4
        with:
          path: configRepo

      - name: Sync labels - Config file
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const syncLabels = require('./configRepo/.github/scripts/sync-labels');
            const deleteUnmatched = '${{ github.event.inputs.deleteUnmatched }}' === 'Delete Unmatched';
            await syncLabels({ github, context, core }, deleteUnmatched);

      - name: Sync labels - Success
        run: echo ✅ Success! This job has completed successfully!
